name: Dockerization of FireWhere
on: push

jobs:
  docker-firewhere:
    name: Build docker container for firewhere
    runs-on: ubuntu-latest
    steps:
      - name: Checkout firewhere code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build firewhere backend Docker image
        run:
          docker build backend --file backend/dockerfile --tag firewherebackend:${{ github.run_number }}
      - name: Tag firewhere backend Docker image 
        run:
          docker tag firewherebackend:${{ github.run_number }} ${{ secrets.DOCKER_REPONAME }}:firewherebackend_v${{ github.run_number }}
      - name: Publish firewhere backend Docker image to docker hub
        run:
          docker push ${{ secrets.DOCKER_REPONAME }}:firewherebackend_v${{ github.run_number }}
      - name: Build firewhere frontend Docker image
        run:
          docker build frontend --file frontend/dockerfile --tag firewherefrontend:${{ github.run_number }}
      - name: Tag firewhere frontend Docker image 
        run:
          docker tag firewherefrontend:${{ github.run_number }} ${{ secrets.DOCKER_REPONAME }}:firewherefrontend_v${{ github.run_number }}
      - name: Publish firewhere frontend Docker image to docker hub
        run:
          docker push ${{ secrets.DOCKER_REPONAME }}:firewherefrontend_v${{ github.run_number }}